apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-gateway-config
  namespace: {{ include "payments-gateway.namespace" . }}
  labels:
    {{- include "payments-gateway.labels" . | nindent 4 }}
data:
  ASPNETCORE_HTTP_PORTS: {{ .Values.config.aspNetCoreHttpPorts | quote }}
  ASPNETCORE_URLS: {{ .Values.config.aspNetCoreUrls | quote }}
  Stripe__PublishableKey: {{ .Values.stripe.publishableKey | quote }}
  {{- range $key, $product := .Values.products }}
  Products__{{ $product.slug }}__PriceId: {{ $product.priceId | quote }}
  Products__{{ $product.slug }}__TrialPeriodDays: {{ $product.trialPeriodDays | quote }}
  Products__{{ $product.slug }}__SuccessUrl: {{ $product.successUrl | quote }}
  Products__{{ $product.slug }}__CancelUrl: {{ $product.cancelUrl | quote }}
  Products__{{ $product.slug }}__PortalReturnUrl: {{ $product.portalReturnUrl | quote }}
  {{- end }}
  RabbitMQ__HostName: {{ .Values.rabbitmq.hostName | quote }}
  RabbitMQ__Port: {{ .Values.rabbitmq.port | quote }}
  RabbitMQ__VirtualHost: {{ .Values.rabbitmq.virtualHost | quote }}
  RabbitMQ__ExchangeName: {{ .Values.rabbitmq.exchangeName | quote }}
  RabbitMQ__ExchangeType: {{ .Values.rabbitmq.exchangeType | quote }}
  Jwt__Authority: {{ .Values.jwt.authority | quote }}
  Jwt__Audience: {{ .Values.jwt.audience | quote }}
